# Generated by Django 6.0.7 on 2026-07-28 20:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_purchase', models.PositiveIntegerField()),
                ('max_purchase', models.PositiveIntegerField()),
                ('prize_type', models.CharField(choices=[('Cash', 'Cash'), ('Product', 'Product')], default='Cash', max_length=10)),
                ('min_reward', models.PositiveIntegerField(blank=True, null=True)),
                ('max_reward', models.PositiveIntegerField(blank=True, null=True)),
                ('purchase_product', models.CharField(max_length=100)),
                ('buy_quantity', models.PositiveIntegerField(default=11)),
                ('reward_product', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FreeRewardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_product', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('given_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.plumber')),
            ],
            options={
                'verbose_name': 'Free Reward History',
                'verbose_name_plural': 'Free Reward History',
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('rate', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('purchase_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.plumber')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ScratchCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_amount', models.PositiveIntegerField()),
                ('reward_type', models.CharField(choices=[('Cash', 'Cash'), ('Product', 'Product')], default='Cash', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('reward_text', models.CharField(max_length=100)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_scratched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.plumber')),
                ('reward_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.rewardrule')),
            ],
        ),
    ]
