# Generated by Django 6.0.7 on 2026-07-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scratchcard',
            name='reward_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Product', 'Product')], default='Cash', max_length=10),
        ),
    ]
