# Generated by Django 6.0.7 on 2026-07-30 20:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freerewardhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='freerewardhistory',
            name='given_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='freerewardhistory',
            name='reward_product',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='plumber',
            name='phone',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='purchase_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rewardrule',
            name='max_purchase',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rewardrule',
            name='min_purchase',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rewardrule',
            name='prize_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Product', 'Product')], db_index=True, default='Cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='rewardrule',
            name='purchase_product',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rewardrule',
            name='reward_product',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='scratchcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='scratchcard',
            name='is_scratched',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='scratchcard',
            name='purchase_amount',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='scratchcard',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
